basePath: /
definitions:
  main.OperationRequestItem:
    type: object
  main.ResultItem:
    properties:
      value: {}
      var:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: API для математических и печатных операций.
  title: Operation API
  version: "1.0"
paths:
  /:
    post:
      consumes:
      - application/json
      description: Принимает список математических и печатных операций, выполняет
        их и возвращает результат.
      parameters:
      - description: Список операций
        in: body
        name: operations
        required: true
        schema:
          items:
            $ref: '#/definitions/main.OperationRequestItem'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.ResultItem'
            type: array
        "400":
          description: Неверный запрос
          schema:
            type: string
        "405":
          description: Метод не поддерживается
          schema:
            type: string
      summary: Выполнить список операций
swagger: "2.0"
